name: Generate Snake Animation

on:
  schedule:
    # Chạy mỗi 12 giờ
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: lethien999
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Push to output branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd dist
          git init
          git add -A
          git commit -m "🐍 Update snake animation"
          git push -f https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/lethien999/lethien999.git HEAD:output
